### ISSUE TITLE
Turn Off Fins After ~45 Seconds Of Flight Time

### ISSUE THREAD

**Issue by natronics** [psas/av3-fc#18]
The Servo should turn off after the flight. The ascent can never be longer than 45 seconds.

**Comment by IanOsgood** [comment]
Already handled: https://github.com/psas/av3-fc/commit/c2f9b01797bac210dcfe7dbd8e1778729f378b5e

But when I asked Andrew, he suggested a two minute timeout.  Adjust rollcontrol.c:TIMEOUT to taste.

**Comment by natronics** [comment]
Thanks!
